version: "3.9"
services:
  s3:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z
    restart: unless-stopped
    container_name: mlflow_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
    networks:
      - internal
      - public
    volumes:
      - ${MINIO_DATA_PATH}:/data
      - ${MINIO_DATA_BACKUP_PATH}:/backup/minio
  db:
    image: postgres:14
    restart: unless-stopped
    container_name: mlflow_db
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ${PG_DATA_PATH}:/var/lib/postgresql/data
      - ${PG_DATA_BACKUP_PATH}:/backup/mlflow_db
    networks:
      - internal
  mlflow:
    image: bitnami/mlflow:2.14.0
    container_name: mlflow_tracker
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USER}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PSWD}
    networks:
      - public
      - internal
    entrypoint: mlflow server --backend-store-uri postgresql://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DATABASE} --default-artifact-root s3://${AWS_BUCKET_NAME}/ --artifacts-destination s3://${AWS_BUCKET_NAME}/ -h 0.0.0.0
    depends_on:
      - "db"
  create_s3_buckets:
    image: minio/mc
    depends_on:
      - "s3"
    entrypoint: >
      /bin/sh -c " until (/usr/bin/mc alias set minio http://s3:9000 '${AWS_ACCESS_KEY_ID}' '${AWS_SECRET_ACCESS_KEY}') do echo '...waiting...' && sleep 1; done; /usr/bin/mc mb minio/${AWS_BUCKET_NAME}; exit 0; "
    networks:
      - internal
  run_test_experiment:
    build:
      context: ./test_experiment
      dockerfile: Dockerfile
    platform: linux/amd64 # once continuumio/miniconda3:latest image work on native aarch64 (arm), remove this line 
    depends_on:
      - "mlflow"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    entrypoint: >
      /bin/sh -c " python3 mlflow_tracking.py; exit 0; "
    networks:
      - internal
  backup_service:
    build:
      context: ./backup_data
      dockerfile: Dockerfile
    container_name: mlflow_backup_service
    restart: unless-stopped
    environment:
      - PG_USER=${PG_USER}
      - PG_DATABASE=${PG_DATABASE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./backup_data/mlflow_backup_cron:/etc/crontabs/mlflow_backup_cron
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MINIO_DATA_BACKUP_PATH}:/backup/minio
      - ${PG_DATA_BACKUP_PATH}:/backup/mlflow_db
    networks:
      - internal
    depends_on:
      - "db"
      - "s3"
networks:
  internal:
  public:
    driver: bridge
